# Generated by Django 3.1.2 on 2020-10-26 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='lead',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
