# Generated by Django 3.1.2 on 2020-10-27 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20201027_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('CSS', 'CSS'), ('JavaScript', 'JavaScript'), ('Python', 'Python'), ('HTML', 'HTML'), ('Web Design', 'Web Design'), ('Tutorials', 'Tutorials')], default='uncategorized', max_length=255, null=True),
        ),
    ]
